/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Text, View } from "@aws-amplify/ui-react";
export default function SignupPage(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1417px"
      height="1628px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "SignupPage")}
      {...rest}
    >
      <View
        width="1417px"
        height="1628px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(217,217,217,1)"
        {...getOverrideProps(overrides, "Rectangle 4")}
      ></View>
      <Text
        fontFamily="Josefin Sans"
        fontSize="64px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="64px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="247px"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="7.68%"
        bottom="88.39%"
        left="41.28%"
        right="41.28%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sign Up"
        {...getOverrideProps(overrides, "Sign Up315")}
      ></Text>
      <View
        width="1161px"
        height="125px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="16.15%"
        bottom="76.17%"
        left="9.03%"
        right="9.03%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(187,204,209,1)"
        {...getOverrideProps(overrides, "Rectangle 5")}
      ></View>
      <View
        width="1161px"
        height="125px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="28.38%"
        bottom="63.94%"
        left="9.03%"
        right="9.03%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(187,204,209,1)"
        {...getOverrideProps(overrides, "Rectangle 6")}
      ></View>
      <View
        width="1161px"
        height="125px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="52.83%"
        bottom="39.5%"
        left="9.03%"
        right="9.03%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(187,204,209,1)"
        {...getOverrideProps(overrides, "Rectangle 7")}
      ></View>
      <View
        width="1161px"
        height="125px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="40.6%"
        bottom="51.72%"
        left="9.03%"
        right="9.03%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(187,204,209,1)"
        {...getOverrideProps(overrides, "Rectangle 8")}
      ></View>
      <View
        width="1161px"
        height="125px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="65.05%"
        bottom="27.27%"
        left="9.03%"
        right="9.03%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(187,204,209,1)"
        {...getOverrideProps(overrides, "Rectangle 9")}
      ></View>
      <Text
        fontFamily="Josefin Sans"
        fontSize="32px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="32px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="214px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="13.7%"
        bottom="83.84%"
        left="7.27%"
        right="77.63%"
        transformOrigin="top left"
        transform="rotate(-0.54deg)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Full Name"
        {...getOverrideProps(overrides, "Full Name")}
      ></Text>
      <Text
        fontFamily="Josefin Sans"
        fontSize="32px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="32px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="214px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.05%"
        bottom="71.5%"
        left="4.73%"
        right="80.17%"
        transformOrigin="top left"
        transform="rotate(-0.54deg)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Email"
        {...getOverrideProps(overrides, "Email")}
      ></Text>
      <Text
        fontFamily="Josefin Sans"
        fontSize="32px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="32px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="214px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="38.15%"
        bottom="59.4%"
        left="7.27%"
        right="77.63%"
        transformOrigin="top left"
        transform="rotate(-0.54deg)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Username"
        {...getOverrideProps(overrides, "Username")}
      ></Text>
      <Text
        fontFamily="Josefin Sans"
        fontSize="32px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="32px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="214px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="50%"
        bottom="47.54%"
        left="7.27%"
        right="77.63%"
        transformOrigin="top left"
        transform="rotate(-0.54deg)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Password"
        {...getOverrideProps(overrides, "Password")}
      ></Text>
      <Text
        fontFamily="Josefin Sans"
        fontSize="32px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="32px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="277.33px"
        height="40px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="62.57%"
        bottom="34.97%"
        left="9.03%"
        right="71.4%"
        transformOrigin="top left"
        transform="rotate(-0.54deg)"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Retype Password"
        {...getOverrideProps(overrides, "Retype Password")}
      ></Text>
      <View
        width="802px"
        height="165px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="77.27%"
        bottom="12.59%"
        left="21.74%"
        right="21.67%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(64,114,149,1)"
        {...getOverrideProps(overrides, "Rectangle 10")}
      ></View>
      <Text
        fontFamily="Josefin Sans"
        fontSize="48px"
        fontWeight="400"
        color="rgba(255,255,255,1)"
        lineHeight="48px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="80.9%"
        bottom="16.15%"
        left="43.82%"
        right="43.82%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sign Up"
        {...getOverrideProps(overrides, "Sign Up3218")}
      ></Text>
      <View
        width="52px"
        height="49px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="91.03%"
        bottom="5.96%"
        left="24.98%"
        right="71.35%"
        border="1px SOLID rgba(0,0,0,0)"
        boxShadow="0px 4px 4px rgba(0, 0, 0, 0.25)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(170,206,249,1)"
        {...getOverrideProps(overrides, "Rectangle 11")}
      ></View>
      <Text
        fontFamily="Josefin Sans"
        fontSize="48px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="48px"
        textAlign="center"
        display="block"
        direction="column"
        justifyContent="unset"
        width="605px"
        height="88px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="90.36%"
        bottom="4.24%"
        left="32.82%"
        right="24.49%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="By clicking here, you agree to the Terms of Agreement"
        {...getOverrideProps(
          overrides,
          "By clicking here, you agree to the Terms of Agreement"
        )}
      ></Text>
    </View>
  );
}
