export const tool_function_categories_cleaner_dict = {
  "Industrial Control Systems": "Industrial_Control_Systems",
  "Cybersecurity Service Provider": "Cybersecurity_Service_Provider",
  "Virtual Private Network": "Virtual_Private_Network",
  "Aircraft Log & Anomaly Detection Tools": "Log_Analysis",
  "Firewall and Network Security": "Firewall_Network_Security",
  "Secure Communication and Data Encryption":
    "Secure_Communication_Data_Encryption",
  "Access Control and Identity Management":
    "Access_Control_Identity_Management",
  "Security Information and Event Management (SIEM) Systems":
    "Security_Information_Event_Management_Systems",
  "Vulnerability Management": "Vulnerability_Management",
  "Threat Intelligence Platforms": "Threat_Intelligence_Platforms",
  "Supply Chain Risk Management Solution":
    "Supply_Chain_Risk_Management_Solution",
  "Regulatory Compliance Tools": "Regulatory_Compliance_Tools",
  "Aviation Focused Tools": "Aviation_Focused_Tools",
  "General Tools": "General_Tools",
  "Endpoint Security": "Endpoint_Security",
};
export const filterOptionsForCompany = {
  Airbus: "Airbus",
  Jepperson: "Jepperson",
  Cisco: "Cisco",
  Fortinet: "Fortinet",
  "Check Point": "Check_Point",
  SonicWall: "SonicWall",
  Sophos: "Sophos",
  WatchGuard: "WatchGuard",
  "Palo Alto": "Palo_Alto",
  McAfee: "McAfee",
  Darktrace: "Darktrace",
  Vectra: "Vectra",
  VMWare: "VMWare",
  Cylance: "Cylance",
  Bitdefender: "Bitdefender",
  Fidelis: "Fidelis",
  SentinelOne: "SentinelOne",
  Tanium: "Tanium",
  CrowdStrike: "CrowdStrike",
  Okta: "Okta",
  Microsoft: "Microsoft",
  Ping: "Ping",
  Splunk: "Splunk",
  IBM: "IBM",
  Tenable: "Tenable",
  Rapid7: "Rapid7",
  ThreatConnect: "ThreatConnect",
  Mandiant: "Mandiant",
  Anomali: "Anomali",
  "Recorded Future": "Recorded_Future",
  MasterCard: "MasterCard",
  Tripwire: "Tripwire",
  SolarWinds: "SolarWinds",
  CyberArk: "CyberArk",
  Fireye: "Fireye",
  "Palo Alto Networks": "Palo_Alto_Networks",
  WithSecure: "WithSecure",
  "Trendo Micro": "Trendo_Micro",
  Claroty: "Claroty",
  "Nozomi Networks": "Nozomi_Networks",
  Dragos: "Dragos",
  "ForeScout Technologies": "ForeScout_Technologies",
  Boeing: "Boeing",
  "AT&T": "AT&T",
  CISCO: "CISCO",
  "United Technologies": "United_Technologies",
};
