[workspace]

members = [
    "beginreportcybertool",
    "recommendTools",
    #"getAllTools",
    #"getreportlist",
    "getsingulartooldata",
    "reportcreatepresignedurl",
    #"reportcybertool",
]

resolver = "2"
