name: 'Frontend build'
on: [push]

jobs:
  test:
    name: npm run build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v1

    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: configure and build
      working-directory: ./code/websitesrc/cybertoolwebsite/
      run: |
        npm install -g @aws-amplify/cli --force
        # Reverse working dir path to root
        ../../../.github/workflows/amplify_pull.sh
        npm install --force # TODO(troy): remove --force
        npm run build
        # npm run test # TODO: re-enable when we actually have tests, until then I will be judging you very hard!
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        # If set to true (default by actions) warnings are treated as errors and we have too many of these to fix rn
        # TODO(troy): force the frontend team to use ES Lint and fix all warnings
        CI: false

